### ISSUE TITLE
The site's top-menu bar is broken

### ISSUE THREAD

**Issue by majix560** [Electrical-Age/electrical-age.github.io#4]
electrical-age.net's top menu bar is broken.
The corner ribbon button to the github works.
However the three top menu bar buttons/links saying "Download", "Wiki", and "Forum" do absolutely nothing.
They literally do nothing but just sit there for you to look at.
The corner ribbon button at the top-right corner works.
And all other links work.
It is only the three previously mentioned top menu bar items near the top right corner that don't work.

**Comment by metc** [comment]
The three links "Download", "Wiki" and "Forum" are working for me.
Could you give me a bit more details ? Which browser do you use ?

**Comment by majix560** [comment]
FireFox

**Comment by lambdaShade** [comment]
Effectively. When the navigator window have a low width (< ~1180 pixels), the title texts go under the ELN icon and the buttons are no more functional (excepting the Github ribbon). Tested on Firefox and Chrome.

**Comment by metc** [comment]
Now the Github ribbon is hidden on "Extra small devices (<768px)" and the top menu is more responsive. Try to resize the window width to test this.
Feel free to reopen the issue if necessary.

**Comment by metc** [comment]
Still need some work to be full mobile responsive, but broken links are fixed now.
