### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by metc** [Electrical-Age/electrical-age.github.io#8]
As @Baughn suggest in PR #7, we should serve the website using HTTPS. 

One option to do this would be to use the Flexible SSL option available for free from CloudFlare. More informations are available here: https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html

@cm0x4D what is your opinion about this ?

**Comment by cm0x4D** [comment]
It is just a static page that everyone can download, why should we encrypt the payload at all? I guess HTTP2 might be actually more interesting than encryption...

**Comment by Baughn** [comment]
Mostly so HTTP2 will work. I like to encrypt everything by default, though, which is very easy nowadays.

**Comment by Baughn** [comment]
Ref: https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure

**Comment by cm0x4D** [comment]
The data exchanged between CloudFlare and Github would still be plain text. So if we want to encrypt seriously we need to switch from Github pages to another hosting service.

**Comment by metc** [comment]
Yes, true. This setup is not fully secure.
I will switch to CloudFlare (https://blog.cloudflare.com/introducing-universal-ssl/) to enable HTTPS support and hopefully HTTP/2 :relaxed:

**Comment by Baughn** [comment]
Github supports HTTPS so long as you're on a github.io domain. So you can point CloudFlare at https://electrical-age.github.io, and it'll work.

**Comment by metc** [comment]
Yes, true. IMHO the custom domain is great and I like to keep it...

**Comment by Baughn** [comment]
You'd get both. electrical-age.net can point at Cloudflare, while Cloudflare proxies through to the github.io version.

**Comment by metc** [comment]
The latest version of https://electrical-age.net/ is up and running using CloudFlare (with SSL and DNSSEC). HTTP/2 is not yet supported...

**Comment by Baughn** [comment]
Actually, Chrome *is* connecting to electrical-age.net using H2. :)

**Comment by metc** [comment]
This site says it doesn't: https://tools.keycdn.com/http2-test
But yes, with Chrome many resources are loaded using h2, great ;)
